#!/bin/zsh

I=0
O="./main.png"
W=1920
H=1080
D=480.0
B=0
C="matte-black"

help(){
	printf "FLAGS FOR TIKZTOPNG" | fmt -c
	printf "\t-I input file or tikz command" | fmt -t 8
	printf "\t-O outpput file(default main.png)" | fmt -t 8
	printf "\t-W width in pxl(default 1920)" | fmt -t 8
	printf "\t-H height in pxl(default 1080)" | fmt -t 8
	printf "\t-D dpi (default 480.0)" | fmt -t 8
	printf "\t 320, 480 dpi for normalsized equation" | fmt -t 12
	printf "\t 640, 800, 1280 for zoom-in effect" | fmt -t 12
	printf "\t-B background color (default transparent)" | fmt -t 8
	printf "\t-C foreground color (default matte-black)" | fmt -t 8
}


show_progress(){
	( echo $1 & progress_bar 50 $2 ) && echo "\n"
}


prepare_resources(){
	mkdir  ./temp
	touch ./temp/main.tex
	touch ./temp/tikzpicture.tex
	cp $I ./temp/input.tex
}


extract_tikz(){
	extracttikzpicture input.tex tikzpicture.tex
}

assemble_tex(){
	echo "\\\documentclass{article}" >> $1
	echo "\\\usepackage{geometry}" >> $1
	echo "\\\usepackage{vaibhavblayer}" >> $1
	echo "\\\geometry{paperwidth=$(($W/$D))in, paperheight=$(($H/$D))in, top=0mm, bottom=3mm}" >> $1
	echo "\\\begin{document}" >> $1
	if [[ $B != 0 ]]
	then
		echo "\\\pagecolor{$B}" >> $1
	else
		echo "\\\nopagecolor" >> $1
	fi
	echo "\\\color{$C}" >> $1
	echo "\\\vspace*{\\\fill}" >> $1
	echo "\\\begin{center}" >> $1
	echo "\\\input{tikzpicture.tex}" >> $1
	echo "\\\end{center}" >> $1
	echo "\\\vspace*{\\\fill}" >> $1
	echo "\\\end{document}" >> $1
}


render_pdf(){
	pdflatex main.tex
	pdflatex main.tex
}

extract_png(){
	pdftopng -I ./main.pdf -D $D
}

archive_tikz(){
	archived=$(date +%d%m%y%H%M%S).tex

	sudo mv tikzpicture.tex /Users/.archive/tikztopng/$archived
}

delete_temp(){
	rm -r ./temp
}

while getopts :hI:O:W:H:D:B:C:: opt
do
	case "$opt" in
	h) help
	   exit ;;
	I) I=$OPTARG ;;
	O) O=$OPTARG ;;
	W) W=$OPTARG ;;
	H) H=$OPTARG ;;
	D) D=$OPTARG ;;
	B) B=$OPTARG ;;
	C) C=$OPTARG ;;
	*) echo "$opt" ;;
	esac
done


if [[ $I != 0 ]]
then
	#function calls
	(prepare_resources && show_progress "\nPreparing temp directory ..." 0.012 ) &&
	
	cd ./temp &&

	(extract_tikz && show_progress "Extracting tikz ..." 0.012 ) &&
	
	(assemble_tex main.tex && show_progress "Assembling main.tex file ..." 0.012 ) && 
	
	(render_pdf | show_progress "Rendering pdf ..." 0.08 ) && 

	(extract_png | show_progress "Extracting png from main.pdf ..." 0.02 ) && 
	
	(
	archive_tikz && 
	show_progress "Archiving tikzpicture.tex as $archived _into_ \n/Users/.archive/tikztopng" 0.012 
	) && 
	
	cd ../ && 

	cp ./temp/main-001.png $O &&
	show_progress "Copying ./temp/main-001.png as $O ..." 0.012 &&
	
	(delete_temp && show_progress "Deleting the temp directory ..." 0.012 ) &&

	printf "Successfully rendered as $O from $I ." | fmt -c
else
	help
	exit ;
fi





